# Generated by Django 3.2.6 on 2021-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50, verbose_name='Имя')),
                ('schedule', models.ImageField(upload_to='', verbose_name='График')),
                ('interval', models.FloatField(verbose_name='Интервал, t дней')),
                ('step', models.FloatField(verbose_name='Шаг, t часов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'Функция',
                'verbose_name_plural': 'Функции',
                'ordering': ('-created',),
            },
        ),
    ]
