# Generated by Django 3.2.6 on 2021-08-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='function',
            field=models.CharField(max_length=50, verbose_name='Функция'),
        ),
        migrations.AlterField(
            model_name='function',
            name='schedule',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График'),
        ),
    ]
