# Generated by Django 3.2.6 on 2021-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_function_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='function',
            name='schedule',
            field=models.ImageField(blank=True, upload_to='schedules', verbose_name='График'),
        ),
    ]
